FROM ubuntu:22.04 AS builder

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . .

RUN cmake -S . -B cmake-build-release -DCMAKE_BUILD_TYPE=Release
RUN cmake --build cmake-build-release --parallel $(nproc)

EXPOSE 8080

CMD ["./cmake-build-release/bin/metrics"]
