services:
  metrics_app:
    build:
      context: .
      dockerfile: Dockerfile.metrics
    container_name: metrics_app
    ports:
      - "8080:8080"
    networks:
      - monitoring_network

  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - metrics_app
    networks:
      - monitoring_network

  grafana:
    image: grafana/grafana:11.1.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/dashboards/dashboard.json
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./dashboard.json:/etc/grafana/dashboards/dashboard.json
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitoring_network

networks:
  monitoring_network:
    driver: bridge

volumes:
  grafana_data: {}
